export const PRODUCT_FILENAMES = [
    "ACÉM COM OSSO.png",
    "Acém Picado.png",
    "Acém.png",
    "Alcatra Maminha 2.png",
    "Alcatra Maminha.png",
    "Alcatra Peça Inteira.png",
    "Alcatra.png",
    "Asa de Frango.png",
    "Asa.png",
    "Ave Natalina.png",
    "Baby Beef.png",
    "Baita.png",
    "Bife Batido Especial.png",
    "Bife Especial.png",
    "Bife Paris.png",
    "Bife de Figado.png",
    "Bife de Fígado.png",
    "Bife de Pernil.png",
    "Bisteca Bovina.png",
    "Bisteca Copa Lombo.png",
    "Bisteca Ct. Filé.png",
    "Bisteca Especial.png",
    "Bisteca Gaúcha.png",
    "Bisteca Suina Especial.png",
    "Bisteca Suína Especial.png",
    "Bisteca Suína Grill.png",
    "Bisteca da Copa.png",
    "Bisteca do Contra Filé.png",
    "Bisteca do Ct. Filé.png",
    "Bisteca do Lombo.png",
    "Bisteca do Sete.png",
    "Bucho Bovino 2.png",
    "Bucho Bovino.png",
    "COXA-COM-SOBRECOXA.png",
    "Calabresa SoftPig.png",
    "Calabresa.png",
    "Capa de Coxão Mole.png",
    "Carne Moida Especial.png",
    "Carne de Panela.png",
    "Carne de Sol.png",
    "Chuletinha.png",
    "Chã Bovino.png",
    "Contra Filé Peça.png",
    "Contra Filé.png",
    "Coração de Boi.png",
    "Costela Bovina B.png",
    "Costela Bovina.png",
    "Costela Recheada.png",
    "Costela.png",
    "Costelinha Picada.png",
    "Costelinha Pururuca.png",
    "Costelinha Salgada.png",
    "Costelinha Suína.png",
    "Coxa Desossada.png",
    "Coxa com Sobrecoxa.png",
    "Coxa de Frano.png",
    "Coxa na Mostarda.png",
    "Coxa.png",
    "Coxinha da Asa.png",
    "Coxão Duro.png",
    "Coxão Mole Bife.png",
    "Coxão Mole.png",
    "Dalia.png",
    "Energetico Bally.png",
    "Entranhas Bovina com flocos de milho vaporizados.png",
    "Entranhas Bovina.png",
    "Espetinho Assado.png",
    "Espetinho Bovino.png",
    "Espetinho Frango.png",
    "Espetinho Kafta.png",
    "Espetinho Panceta.png",
    "Espetinho de Coração.png",
    "Espetinho de Kafta.png",
    "Espetinho de Linguiça.png",
    "Espetinho de Panceta.png",
    "Espetinho de Tulipa.png",
    "Espetinho_Carne.png",
    "Espetinho_Porcoes_PNG_Transparente.png",
    "Espeto Assado.png",
    "Feed.png",
    "Festivo.png",
    "Figado de Frango.png",
    "File Mignon Suino.png",
    "File de Coxa.png",
    "Filé Mignon Suíno.png",
    "Filé Mignon.png",
    "Filé de Coxa 2.png",
    "Filé de Coxa.png",
    "Filé de Frango.png",
    "Filé de Sobrecoxa.png",
    "Fraldinha.png",
    "Frango Assado.png",
    "Frango Festivo.png",
    "Frango Fiesta Seara.png",
    "Frango Resfriado.png",
    "Frango a Passarinho sem tempero.png",
    "Frango a Passarinho.png",
    "Frangão Foods.png",
    "Frangão.png",
    "Fressura.png",
    "Fígado Bovino.png",
    "Fígado de Frango.png",
    "Galo Caipira.png",
    "Garrão.png",
    "Hambúrguer.png",
    "Itabom.png",
    "Joelho Suino.png",
    "Joelho Suíno.png",
    "Joelho Suíno.png",
    "Kit Feijoada.png",
    "Lagarto Bife.png",
    "Lagarto Plano.png",
    "Lagarto Redondo.png",
    "Leite Aurora.png",
    "Leitoa.png",
    "Linguiça Apimentada.png",
    "Linguiça Aurora.png",
    "Linguiça Caipira.png",
    "Linguiça Calabresa.png",
    "Linguiça Fina Pernil.png",
    "Linguiça Toscana pra Churrasco.png",
    "Linguiça Toscana.png",
    "Linguiça com Rúcula.png",
    "Linguiça de Frango Grossa.png",
    "Linguiça de Frango.png",
    "Linguiça de Pernil Grossa.png",
    "Linguiça de Pernil.png",
    "Lombo Bovino.png",
    "Lombo Recheado.png",
    "Lombo Suino.png",
    "Lombo Suíno.png",
    "Língua de Boi.png",
    "Maes.png",
    "Medalhão Filé Mignon.png",
    "Medalhão de Frango.png",
    "Mini Chicken.png",
    "Mini Chiken.png",
    "Miolo da Paleta.png",
    "Miolo de Alcatra Bife.png",
    "Miolo de Alcatra.png",
    "Miolo do Acem com Osso.png",
    "Miolo do Acém Grill.png",
    "Miolo do Acém com Osso.png",
    "Mocoto Bovino.png",
    "Mocotó.png",
    "Mocotó2.png",
    "Moela de Frango.png",
    "Moela.png",
    "Mortadela.png",
    "Moída Especial.png",
    "Moída Extra Magra.png",
    "Musculo.png",
    "Músculo.png",
    "Nuggets.png",
    "Orelha Suína Fresca.png",
    "Orelha de Porco.png",
    "Osso Buco.png",
    "Ovos.png",
    "Paleta.png",
    "Panceta Especial Fatiada.png",
    "Panceta Especial.png",
    "Patinho Bife.png",
    "Patinho Moído.png",
    "Patinho Muido.png",
    "Patinho em Bife.png",
    "Patinho.png",
    "Patinho2.png",
    "Pe de Frango.png",
    "Peito Bovino.png",
    "Peito com Osso.png",
    "Peito de Frango com Osso.png",
    "Peito de Frango sem osso.png",
    "Peito.png",
    "Pernil Fatiado.png",
    "Pernil Picado com Osso.png",
    "Pernil Recheado.png",
    "Pernil.png",
    "Pescoço de Frango.png",
    "Picanha - Copia.png",
    "Picanha Fatiada.png",
    "Picanha Fresca.png",
    "Picanha SuIna.png",
    "Picanha SuÍna.png",
    "Picanha.png",
    "Ponta de Alcatra Bife.png",
    "Ponta de Peito com Osso.png",
    "Ponta de Peito.png",
    "Pá Bovina.png",
    "Pão de Alho Zinho.png",
    "Pé de Porco.png",
    "Queijo Coalho.png",
    "Rabada.png",
    "Rabinho Suíno.png",
    "Rabinho.png",
    "Salsicha Hot Dog.png",
    "Satiare.png",
    "Seara.png",
    "Short Rib.png",
    "Short Ribs.png",
    "Soft Pig.png",
    "Strogonoff de Carne.png",
    "Strogonoff de Frango.png",
    "Suan Bovino.png",
    "Suan Suino.png",
    "Suan Suíno.png",
    "Toucinho Picado.png",
    "Tulipa Temperada.png",
    "Tulipa de frango.png",
    "Tulipa.png",
    "brahma 12.png",
    "coca 2l.png",
    "costelinha picada_1.png",
    "heineken.png",
    "maminha.png",
    "skol 12.png"
];
